name: "CI Pipeline"

trigger:
  branches:
    include:
    - main

pool:
  vmImage: "ubuntu-16.04"


variables:
- name: environment

jobs:
- job: "Infrastructure"
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
  - task: CmdLine@2
    inputs:
      script: |
        terraform version
        ls -la
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\Infra'
      backendType: 'azurerm'
      backendServiceArm: 'SC1'
      backendAzureRmResourceGroupName: 'statefiles-store-rg'
      backendAzureRmStorageAccountName: 'statefilesstore'
      backendAzureRmContainerName: 'storage-lid'
      backendAzureRmKey: 'Infra'
  # - task: TerraformCLI@0
  #   inputs:
  #     command: 'validate'
  #     workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
  
          
  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
      environmentServiceName: 'SC1'
