name: "CI Pipeline"

trigger:
  branches:
    include:
    - infra

pool:
  vmImage: "ubuntu-16.04"


variables:
- name: environment

jobs:
- job: "Terraform Init"
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
