name: "CD Pipeline"

pool:
  vmImage: "ubuntu-latest"

parameters:
- name: tfaction
  displayName: Terraform Action
  type: string
  default: plan
  values:
  - destroy
  - apply
  - plan
  
variables:
  - group: tfvars-pe
  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)
  - name: environmentName
    value: 'Dev'
  - name: tfversion
    value: 'v1.0.1'

stages:        
- stage: Terraform
  displayName: Terraform
  jobs:
  - job: terraformPlan
    displayName: "Terraform Plan"
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: $(tfversion)
    
    - task: TerraformTaskV2@2
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: 'SC1'
        backendAzureRmResourceGroupName: 'statefiles-store-rg'
        backendAzureRmStorageAccountName: 'statefilesstore'
        backendAzureRmContainerName: '$(STATE_FILE_CONTAINER)'
        backendAzureRmKey: '$(STATE_FILE)'

    - task: TerraformTaskV2@2
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

    - task: TerraformTaskV2@2
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'SC1'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    
  - deployment: terraformApply
    displayName: "Terraform Apply"
    dependsOn: terraformPlan
    condition: and(succeeded(), ne('${{ parameters.tfaction }}', 'plan'))
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: $(tfversion)
    
          - task: TerraformTaskV2@2
            displayName: Install Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: 'SC1'
              backendAzureRmResourceGroupName: 'statefiles-store-rg'
              backendAzureRmStorageAccountName: 'statefilesstore'
              backendAzureRmContainerName: '$(STATE_FILE_CONTAINER)'
              backendAzureRmKey: '$(STATE_FILE)'

          - task: TerraformTaskV2@2
            displayName: Terraform ${{ parameters.tfaction }}
            inputs:
              provider: 'azurerm'
              command: ${{ parameters.tfaction }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'SC1'
              # commandOptions: '-var="webapp_name=$(webAppName)" -var="storageaccname=$(storageAccName)" -var="rg_name=$(rgName)"'

# - stage: blobDataUpload
#   displayName: "Data Upload"
#   condition: and(succeeded(), eq('${{ parameters.tfaction }}', 'apply'))
#   jobs:
#   - job: blobDataUpload
#     displayName: Upload sample data
#     steps:
#       - task: Bash@3
#         displayName: "Getting Build Agent IP"
#         inputs:
#           targetType: 'inline'
#           script: |
#             IP=`curl -s http://ipinfo.io/json | jq '.ip'`
#             echo '##vso[task.setvariable variable=buildagentip]$IP'
#             echo 'Build agent IP is $IP'
#       - task: AzureCLI@2
#         displayName: "Sample Data Copy"
#         inputs:
#           azureSubscription: 'SC1'
#           scriptType: 'bash'
#           scriptLocation: 'inlineScript'
#           inlineScript: |
#             az storage account network-rule add --account-name '$(TF_VAR_STR_ACC_NAME)' -g '$(TF_VAR_RG_NAME)' --ip-address $(buildagentip)
#             az storage container create --name 'org' --account-name '$(TF_VAR_STR_ACC_NAME)'
#             az storage container create --name 'users' --account-name '$(TF_VAR_STR_ACC_NAME)'
#             az storage blob sync -c 'org' --account-name '$(TF_VAR_STR_ACC_NAME)' -s '$(System.DefaultWorkingDirectory)/sampledata/org'
#             az storage blob sync -c 'users' --account-name '$(TF_VAR_STR_ACC_NAME)' -s '$(System.DefaultWorkingDirectory)/sampledata/users'
#             az storage account network-rule remove --account-name '$(TF_VAR_STR_ACC_NAME)' -g '$(TF_VAR_RG_NAME)' --ip-address $(buildagentip)
      
- stage: Build
  displayName: Build App
  condition: and(succeeded(), eq('${{ parameters.tfaction }}', 'apply'))
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(TF_VAR_PY_VERSION)'
      displayName: 'Use Python $(TF_VAR_PY_VERSION)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)/App
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)/App'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: and(succeeded(), eq('${{ parameters.tfaction }}', 'apply'))
  jobs:
  - deployment: DeploymentJob
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(TF_VAR_PY_VERSION)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : $(TF_VAR_WEB_APP_NAME)'
            inputs:
              azureSubscription: 'SC1'
              appType: 'webAppLinux'
              appName: '$(TF_VAR_WEB_APP_NAME)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: format('PYTHON|{0}',$(TF_VAR_PY_VERSION))

