name: "CD Pipeline"

trigger:
  branches:
    include:
    - secure

pool:
  vmImage: "ubuntu-latest"

parameters:
- name: tfaction
  displayName: Terraform Action
  type: string
  default: plan
  values:
  - destroy
  - apply
  - plan
  
variables:
  - group: tfvars
  - name: webAppName
    value: 'storage-lid-pe'
  - name: storageAccName
    value: 'orguserdatastorepe'
  - name: rgName
    value: 'storage-lid-pe-rg'
  - name: environmentName
    value: 'dev'
  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)
  - name: pythonVersion
    value: '3.7'

stages:
- stage: Terraform
  displayName: Terraform
  jobs:
  - job: terraformJob
    displayName: "Terraform Job"
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'v0.14.9'

    - task: TerraformCLI@0
      displayName: Terraform Init
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendType: 'azurerm'
        backendServiceArm: 'SC1'
        backendAzureRmResourceGroupName: 'statefiles-store-rg'
        backendAzureRmStorageAccountName: 'statefilesstore'
        backendAzureRmContainerName: 'storage-lid'
        backendAzureRmKey: 'terraform.tfstate'
    
    - task: TerraformCLI@0
      displayName: Terraform Validate
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        
    - task: TerraformCLI@0
      displayName: Terraform Plan
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: SC1
        commandOptions: '-var="webapp_name=$(webAppName)" -var="storageaccname=$(storageAccName)" -var="rg_name=$(rgName)"'
    # - task: ManualIntervention@8
    #   inputs:
    #     instructions: 'Please review before ${TERRAFORM_ACTION}'
    #     emailRecipients: 'iamdhishan@gmail.com'
    #     onTimeout: reject
    - task: TerraformCLI@0
      displayName: Terraform Apply
      inputs:
        command: ${{ parameters.tfaction }}
        workingDirectory: 'terraform'
        environmentServiceName: SC1
        commandOptions: '-var="webapp_name=$(webAppName)" -var="storageaccname=$(storageAccName)" -var="rg_name=$(rgName)"'

- stage: blobDataUpload
  displayName: "Data Upload"
  condition: and(succeeded(), eq('${{ parameters.tfaction }}', 'apply'))
  jobs:
  - job: blobDataUpload
    displayName: Upload sample data
    steps:
      - task: AzureCLI@2
        displayName: "Org Sample Data Copy"
        inputs:
          azureSubscription: 'SC1'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob sync -c 'org' --account-name 'orguserdatastore' -s '$(System.DefaultWorkingDirectory)/sampledata/org'
      
      - task: AzureCLI@2
        displayName: "Users Sample Data Copy"
        inputs:
          azureSubscription: 'SC1'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob sync -c 'users' --account-name 'orguserdatastore' -s '$(System.DefaultWorkingDirectory)/sampledata/users'

- stage: Build
  displayName: Build stage
  condition: and(succeeded(), eq('${{ parameters.tfaction }}', 'apply'))
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)/App
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)/App'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: and(succeeded(), eq('${{ parameters.tfaction }}', 'apply'))
  jobs:
  - deployment: DeploymentJob
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : $(webAppName)'
            inputs:
              azureSubscription: 'SC1'
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip

