name: "CI Pipeline"

trigger:
  branches:
    include:
    - infra

pool:
  vmImage: "ubuntu-16.04"


variables:
- name: environment

jobs:
- job: "Infrastructure"
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      environmentServiceName: 'Visual Studio Enterprise (c996be46-cd38-4bdf-8180-17d60b8e8e53)'
