name: "CI Pipeline"

trigger:
  branches:
    include:
    - main

pool:
  vmImage: "ubuntu-16.04"


variables:
- name: environment

jobs:
- job: "Infrastructure"
  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
  # - task: TerraformCLI@0
  #   inputs:
  #     command: 'validate'
  #     workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
  # - task: CmdLine@2
  #   inputs:
  #     script: |
  #       pwd
  #       ls -la
          
  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
      environmentServiceName: 'SC1'
